"""Crear tabla cuentas

Revision ID: e06b6606785f
Revises: 
Create Date: 2026-09-03 09:58:39.805174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06b6606785f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('num_cuenta', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuentas_correo'), ['correo'], unique=True)
        batch_op.create_index(batch_op.f('ix_cuentas_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_cuentas_num_cuenta'), ['num_cuenta'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuentas_num_cuenta'))
        batch_op.drop_index(batch_op.f('ix_cuentas_documento'))
        batch_op.drop_index(batch_op.f('ix_cuentas_correo'))

    op.drop_table('cuentas')
    # ### end Alembic commands ###
